version: 2.1

orbs:
  python: circleci/python@2.1
  codecov: codecov/codecov@3.2

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

commands:
  install-dependencies:
    steps:
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -e ".[dev,test]"

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Run linting checks
          command: |
            . venv/bin/activate
            black --check src tests
            flake8 src tests
            isort --check-only src tests
            mypy src

  test:
    executor: python-executor
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir -p test-results/pytest
            pytest --junitxml=test-results/pytest/results.xml tests/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  build:
    executor: python-executor
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Build package
          command: |
            . venv/bin/activate
            python setup.py sdist bdist_wheel
      - store_artifacts:
          path: dist
          destination: dist

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
          filters:
            branches:
              only: main
