# .circleci/config.yml
version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      
      # Create and activate virtual environment
      - python/install-packages:
          pkg-manager: pip
          # Create a virtual environment
          venv-create: true
          # Use requirements.txt for dependencies
          pip-dependency-file: requirements/dev.txt
          
      # Run tests
      - run:
          name: Run tests
          command: |
            python -m pytest tests/ -v

      # Store test results
      - store_test_results:
          path: test-results

      # Store test reports
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build-and-test
