# .circleci/config.yml
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      # Set up Python virtual environment and install dependencies
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements/dev.txt

      # Run tests
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python -m pytest tests/ -v

      # Store test results
      - store_test_results:
          path: test-results

      # Store test artifacts
      - store_artifacts:
          path: test-results
          destination: tr1

workflows:
  main:
    jobs:
      - build-and-test
